### ISSUE TITLE
header is squished on mobile view

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#1023]
![Screenshot_20220729-131939_Chrome](https://user-images.githubusercontent.com/55995241/181811594-051bc851-495e-48ff-b6a5-edd4ac636664.jpg)

**Comment by brianwdavis** [comment]
There's some minimum width hardcoded that's not great, see this screen recording from a Pixel 5a.

https://user-images.githubusercontent.com/13338560/184410917-d26b895d-6790-45dd-8736-0f3049267114.mp4
