### ISSUE TITLE
farm code title on water sensor view window

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#103]
when you click on the farm code in the water sensor view, you see the serial number of the nodes but, not the farm code, and that would be helpful to see in the page

**Comment by saseehav** [comment]
voltage spelled wrong
water content and signal strength and voltage are most important
delete depth
restrict graphs to current year and season, ie: start April 1?

**Comment by saseehav** [comment]
Example of why we need to restrict graphs to specific years and dates
![nodegraphvoltageexample](https://user-images.githubusercontent.com/49722541/83153184-aaf24c80-a0cc-11ea-8512-9345c430def9.JPG)

**Comment by saseehav** [comment]
How to do Diagnostic View, per Brian's recommendation: sort by year, by farm, all nodes per farm per year, graph on all nodes in query and visuals for all nodes and sensors in that year.

Chris's query issue: confirm that the **node query also comes through the allocation** table so previous years and farms don't show up inside the current year per farm. Add a filter to the query to stay within the year date.

Aurelie's issue:  if the allocation isn't filled correctly, it will show all hardware anyway.

Query order: Water sensors/ farm code/nest subplot and rep inside code/ gateway/ nodes

**Comment by rbandooni** [comment]
@saseehav This issue has been partially resolved [here](https://dev.onfarmtech.org) until the next revamp.
