### ISSUE TITLE
Task tracker links to sources

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#1058]
The element they click on could be the title, or the whole card, or any of the chips. Whatever is easiest.

**Comment by saseehav** [comment]
Site Enrollment >
Address = https://www.onfarmtech.org/site-information/contact-enrollment
Site Coordinates = https://www.onfarmtech.org/site-information/contact-enrollment
GPS Corners = https://www.onfarmtech.org/kobo-forms/ak6HVZZJPwC2EgR3qVWTsA 
Planting Date = https://www.onfarmtech.org/site-information/farm-dates

Biomass >
Fresh Weights = https://www.onfarmtech.org/kobo-forms/a5Do7iYsTxrHxHqqaqcfU9 
Legume Percentage = https://www.onfarmtech.org/kobo-forms/a5Do7iYsTxrHxHqqaqcfU9 
Termination Date = https://www.onfarmtech.org/site-information/farm-dates

Decomp Bags >
Empty wts = https://www.onfarmtech.org/kobo-forms/afHDjP6jCPMGvDDZqDqdyL 
Fresh wts = https://www.onfarmtech.org/kobo-forms/a5Do7iYsTxrHxHqqaqcfU9 
Recovery dates = https://www.onfarmtech.org/kobo-forms/aGCjaJEeADNxfoPZD9rUm7 
Dry wts = https://www.onfarmtech.org/kobo-forms/aGPMTPpqU68JvdHK6Wuejb 

Sensor Installation >
Nodes = https://www.onfarmtech.org/kobo-forms/aixsrhq7hngRuJaPMLCMQy 
Cash Crop Planting date = https://www.onfarmtech.org/site-information/farm-dates 

Yield >
corn hand harvest = https://www.onfarmtech.org/kobo-forms/aK58LtJJkQZx8ZRJ8uyiLq
soy hand harvest = https://www.onfarmtech.org/kobo-forms/aK58LtJJkQZx8ZRJ8uyiLq
cotton hand harvest = https://www.onfarmtech.org/kobo-forms/aK58LtJJkQZx8ZRJ8uyiLq
weigh wagon = https://www.onfarmtech.org/kobo-forms/aK58LtJJkQZx8ZRJ8uyiLq
(those are all the same)

**Comment by saseehav** [comment]
Forms that we are still missing task tracking yet (especially now that the dates editor exists)
- farm history survey - Idea - populate "CC Species"
- corn disease (no idea because we don't import those, so skip)
- forage and uninstall (do we need those?)
