### ISSUE TITLE
form name: empty in form editor

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#1144]
on the tech dashboard kobo form editor, after selecting the form name in the list, the screen opens to a list of forms. the top of the screen has "form name:" but it is blank
<img width="440" alt="image" src="https://user-images.githubusercontent.com/49722541/222772372-23c5dc8f-0c20-47fa-98dd-816e049e7e92.png">

can the name be filled?

**Comment by brianwdavis** [comment]
Appears complete
