### ISSUE TITLE
Task Tracker feature fix - Species

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#1158]
**What's wrong**
-farm codes should be present but grey when data is not there
- farm codes are not populated in species at all

**What done looks like**
-farm codes should be present but grey when data is not there
<img width="839" alt="image" src="https://github.com/precision-sustainable-ag/tech-dashboard/assets/49722541/248c405b-b21a-4482-b86c-aa60996fe85f">

**Comment by brianwdavis** [comment]
This doesn't work because the rows for species aren't pre-filled in the DB since they can be an unknown number.
