### ISSUE TITLE
Re-architect the code->gateway relationship for sensors (instead of current gateway->code relationship)

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#121]
The API calls should be:
---

### Make cards from farm codes
 - Look up `SELECT DISTINCT CODE, SUBPLOT FROM wsensor_install where EXTRACT(YEAR from time_begin) = year_of_active_pane`
 - For each row of that query, make a UI card element with CODE and SUBPLOT

### Get all serials associated with each code
- On card click, a call should look up every row in `wsensor_install` that matches code and subplot (`SELECT * FROM` the "make cards" query, instead of the `SELECT DISTINCT`)
- For each row in this query, look up gateway serials and node serials

### Query data for each serial

- For each serial, make a UI badge with serial and hover text to identify it (current behavior for nodes is correct; need to implement this for gateways as well)
- On badge click, for each serial, look up `water_sensor_data` (or `water_gateway_data`) where serial=serial and year=year to construct graphs

**Comment by brianwdavis** [comment]
This will break someday as we redeploy a node or gateway within the same year.

To fix this, the "query data for each serial" should be a query like:

```
SELECT * FROM water_sensor_data 
  WHERE node_serial_no = $(each serial) 
    AND timestamp > $(time_begin from wsensor_install query) 
    AND timestamp < COALESCE ($(time_end from wsensor_install query), NOW())
```

I'm not 100% on that query, but the logic is, you want rows from the data tables where the data observation is greater than the `time_begin` from the install table. Then of those rows, you want to keep rows that either have NULL for `time_end`, or where `timestamp` is before `time_end`.

The coalescing with `NOW()` means that NULL values for `time_end` (currently deployed, not yet uninstalled) will be replaced with the current time inside this query.

**Comment by brianwdavis** [comment]
All this logic is now implemented in the API. We need to render the API endpoint on the front end.

**Comment by brianwdavis** [comment]
For each chart currently on view, you'll have a series of checkboxes to overlay options, like showing both cover and bare treatments, to show only one depth, to show one or two subplots ("reps").

**Comment by brianwdavis** [comment]
Notes on the first demo:

Landing page:

- affiliation chips at the top with the years on the card view

Missing data:

- change the text on empty array to "No data available yet, have you installed sensors and filled out a koboform?"
- change button on empty array to go to Tech Dashboard forms view for the "psa water sensor install form" and ask "is your form there and complete? If it looks right to you add a comment to alert us that it didn't parse correctly"
- check node data as well as gateway to see if data is missing (sometimes there's no gateway but there are nodes)

Existing graphs:

- throw away serial numbers, everything returned by a node should be a single node_health panel
- switch to using the `timestamp` column instead of `ts_up`
- reached out to Rick about changing timestamps to Unix [precision-sustainable-ag/API/issues/4]
- don't use `location=true` to get coords


New graphs:

- toggle switches for the `center_depth` column for new panels for VWC and soil temp
- new panel for t_lb from ambient (litter bag temperature, will only be for cover nodes)
- use `&cols=[...]` param on the API calls to choose only the needed columns to cut down on payload size

Map feature (lower priority):

- make API call to `raw?table=wsensor_install&code=XXX` and filter for the last timestamped row for each subplot, which will give you potentially 4 latlongs: subplot 1 and 2, cover and bare each
- on click, render a leaflet or google popup/modal to show where those 4 points are, and they can zoom/pan to make sure that farm is where they think it is

**Comment by brianwdavis** [comment]
Performance fix ideas:


1. Once you've parsed the array from the API into highcharts-friendly format, only use every X index position depending on array length. Example: if length>1000, do every 10th element; if length>500, every 5th element; if length< 100, every element. However, I imagine highcharts doesn't tell you how many points are inside the zoomed area when you zoom in, so you can't do this dynamically easily. We like this option though.
2. See if proper Unix timestamps speeds things up. I'll try to get that onto the API ASAP.
3. VWC and Soil temp should be separate panels, not overlaid. Implement a dropdown or other selector to choose between VWC, soil temp, litterbag temp (t_lb). Also fix the Y axis labels to be appropriate for each metric.
4. Get rid of toggles and instead have four panels for the metrics in  number 3. So you'd have subplot1 bare, subplot1 cover, subplot2 bare, subplot2 cover, always arranged in the same order, and labeled. This option is probably going to fix our visual differentiation problem.

**Comment by brianwdavis** [comment]
Node voltage (battery and solar) should be 4 panels (sub1 bare, etc) as well, since that's four devices out in the field.

**Comment by saseehav** [comment]
Colors for each "center_depth"
"top" = -15
"middle" = -45
"deep" = -80
"surface" = -5
 with legends

Change 'subplot ' to 'rep'

**Comment by brianwdavis** [comment]
Last thing before close, one word change on the charts:

 > Change 'subplot ' to 'rep'
