### ISSUE TITLE
Google location services

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#154]
When enrolling a new site or viewing an existing site, the popup should be a Google map with a searchable box to locate a town etc.

The return from that query should populate the COUNTY column, which should not be hand editable.

**Comment by brianwdavis** [comment]
Actually don't bother with county since we're not using it in the backend right now

**Comment by brianwdavis** [comment]
Is this issue done?

**Comment by rbandooni** [comment]
This has been resolved in PR #334
