### ISSUE TITLE
Assign random codes based on column in `affiliations` table

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#157]
The `affiliations` table will have three columns: `affiliation`, `label`, and `status`.

- Display `label` in the drop down selector.
- Use `affiliation` to construct the producer ID (first two letters).
- Use `status` to assign random codes from the `codes` table that are not currently used:
  - match `[A-Z]{3}` for `"university"`
   - match `[A-Z]{2}[0-9]` for `"partner"`

**Comment by rbandooni** [comment]
Show those codes which don't have numbers for this week.
