### ISSUE TITLE
Feature Request: Missing Data/ Tasks Completed (by site)

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#188]
As techs start leaving the field they want to know, did i submit all my forms for this site? 
the "All Data" view might tell them this, but is there a quick way to see in the dashboard the tasks completed

**Comment by brianwdavis** [comment]
There are two approaches here:

1. Is there data in the appropriate rows for each protocol (this is the one we've put the most thought into and should implement using https://github.com/precision-sustainable-ag/API/issues/49). I want to go ahead and assign this one out.
2. Have the right number of forms been submitted per team user? This one is a little harder to track. Is it just saying "`md_psa` has 4 farms enrolled, so they should be submitting at least 4 copies of `psa_gps` and 20 copies of `psa_bag_collect`, etc". But then how do we check they've submitted enough `bag_pre_wt`? That could be any number of sites mixed together. Do we just go based off the minimum number we expect? We can't (shouldn't) go through and try to extract info out of the forms for this, that's the purpose of number 1.

**Comment by brianwdavis** [comment]
For option 1 above, we should have a sidebar item "Task tracker" that has a number of cards, each with a single protocol. Inside each card should be a title, numeric summary, and some kind of completion meter, could be a pie chart, gas gauge, etc. Mock up some options for us to react to. I think something like -1 = red/"Not available", 0 = yellow/"Missing", 1 = green/"Completed".

- Each card would draw data from `raw?table=$1&year=$2&affiliation=$3&complete_count=$4`. 
- Implement the chips across the top to choose which site-year and affiliation to display, which would be vars 2 and 3. This logic exists elsewhere in the app to show only chips a user has permissions for, e.g. "Biomass > Farm Values"
- An example to use for mocking this up is:
  - Title: "Decomp bag dry weights"
  - table: `decomp_biomass_dry`
  - column: `dry_biomass_wt`
 - A second example would be:
   - Title: "Decomp bag pickups"
   - table: `decomp_biomass_dry`
   - column: `recovery_date` 
  - A third example would be:
    - Title: "GPS corners"
    - table: `gps_corners`
    - column: `latitude` 

On-click, this should expand to show a list of site codes and what the relative proportions are for each one. Eventually we'll add text or more behavior to indicate that people should go look at the forms or to link directly to the data table, but that will vary by card.

**Comment by brianwdavis** [comment]
Additional mockup for thoughts: https://docs.google.com/presentation/d/1S1HxlsRG9r-XBsIkggHL2OWSHcHo4dQV/edit#slide=id.p2

**Comment by brianwdavis** [comment]
All flag = 0 means gray. Mixture of 1 and 0 is yellow. All 1 is green. Ignore -1.

**Comment by brianwdavis** [comment]
@psurana-ncsu I was reviewing the changes you made to make this feature collapsible. I love the vertical collapsing behavior, but now the horizontal layout is buggy.

![image](https://user-images.githubusercontent.com/13338560/157470138-5ab789dc-f719-45eb-bf91-4ef94f67b221.png)

On the non-collapsible version the cards are all a consistent width. When you choose affiliation=='all', they become evenly sized again, but if you choose a single state, like affiliation=='AL', you get my screenshot.

**Comment by mikahpinegar** [comment]
that's a weird bug. it looks great when all affiliations are selected but as soon as you pick one it gets all squished

**Comment by brianwdavis** [comment]
This will be closed with #845, but I'll reopen the next time we want to add cards or change labels
