### ISSUE TITLE
Dashboard Crash: downloading PNG

### ISSUE THREAD

**Issue by alondrathompson** [precision-sustainable-ag/tech-dashboard#203]
I had the dashboard crash multiples times after I zoomed in on a plot and tried to download the PNG. It would go to an error page and so I would have to re-enter the url into my browser. This could be a problem because my laptop is old, but I put it here just in case.

**Comment by rbandooni** [comment]
Thanks for filing the issue @alondrathompson. It would be really helpful if you could add some screenshots or instructions to recreate this issue. 
Also, is this issue just with your laptop or other devices as well?

**Comment by alondrathompson** [comment]
![image](https://user-images.githubusercontent.com/52457672/91740287-1989ef00-eb81-11ea-8cb1-f1fbcacf3f54.png)

**Comment by alondrathompson** [comment]
I also got the error when I tried the same process on my iPhone.

**Comment by brianwdavis** [comment]
Temporary fix is to disable downloads until we spin up our own Highcharts instance
