### ISSUE TITLE
Tech Dashboard not loading on iphone

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/tech-dashboard#225]
Tech dashboard not loading on iphone (5s) have tried Safari, Firefox, Chrome. Stuck on loading screen. 

![image](https://user-images.githubusercontent.com/64480167/91190471-9d476580-e6c1-11ea-9fb1-c1e86c9bd72c.png)

**Comment by rbandooni** [comment]
@annabirnbaum Sorry you’re having this issue on your iPhone with the dashboard. Just curious, could you try opening [onfarmtech.org](https://onfarmtech.org) without the parameters in the URL starting with **?cod..**

**Comment by annabirnbaum** [comment]
I am confused by "URL starting with ?cod.." part of you comment.  I type onfarmtech.org into my browser, put in my github id and password and then it goes to and stays on loading screen.

**Comment by brianwdavis** [comment]
What version iPhone and iOS do you use? We're still trying to pin this down.

**Comment by annabirnbaum** [comment]
Hey,

Was going to tell you today, I noticed yesterday that it is now working. Its an iphone 5...

Thanks!

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
