### ISSUE TITLE
Site Enrollment - New Site Won't Save

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#227]
From Lindsey Ruhl, new state, Vermont: Not knowing how the system works, it seems like the grower needs to be saved before the site can be saved.  So, when I walk through the process the first time I enter grower information then site information (I get a three digit code).  Then walk through the rest of the steps and click confirm.  When I go back to the original site enrollment screen, it shows that I have 0 sites enrolled.  When I look up an existing grower it shows the grower and indicates that no site have been saved.  When I select the grower, it brings me to the site enrollment form.  I walk through the steps, press confirm and then the site is saved.  At the end of the process, I’ve walked through creating two sites, but only one saves.

**Comment by saseehav** [comment]
We've had a few more states have the same issue. 
From Kansas: So instead of trying for a 4th time I decided to “search by last name” and I can see three entries. I am using Google Chrome as my browser. I will quit trying for right now. Peter Tomlinson is going to add another grower from Kansas (last name is Flickner) and so let’s see what happens when he does that. He will be on a different computer than me.

**Comment by brianwdavis** [comment]
Is this related to #171 ?
