### ISSUE TITLE
All Data: Pencil Edit Not active

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#234]
For all the new states, the edit feature from the "All data" view, after enrolling a site is not active. Neither is the trash can for deleting a site

**Comment by brianwdavis** [comment]
Are we using the "edit" in the permissions column in the raw-db for this?

**Comment by brianwdavis** [comment]
We will transition to using the role column for this

**Comment by rbandooni** [comment]
Closing this issue for now. Looks like we would transition over to roles instead.
