### ISSUE TITLE
Site Enrollment - Grower Info - Add a First Name

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#282]
Users are not reading that it says "Last Name" and are instead typing the whole name, messing with our dashboard function.
Maybe add a "First Name" some people don't accidentally type a full name

**Comment by brianwdavis** [comment]
Show `first_name` on producers view, it's already in the DB.

**Comment by brianwdavis** [comment]
Also like Sarah asked, make this a field in "Site Enrollment"
