### ISSUE TITLE
User Roles and Permissions: Edit function

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#285]
Esleyther was not able to use the pencil icon to Edit Site Information like Address.
I updated his Permissions from 'View, Download' to 'View, Download, Edit'.
We need to make distinctions between what is editable for Technicians (ie: farmer address info) and what isn't (ie: data). 
Perhaps we can use the Role distinction of 'Tech' vs 'Data Shepherd' for a set type of permissions, like editing the site info.

Let's talk more on this

**Comment by brianwdavis** [comment]
Create column in `users` table called "states_editable"
@saseehav will fill in
Restrict editing features (site information and producer info) to only those sites.

Example: Esleyther can VIEW "all" states but will only be able to EDIT "NC" states

**Comment by brianwdavis** [comment]
This will be fixed by using the new "global" vs "home" view. Editing will only be allowed while in the "home" view.
