### ISSUE TITLE
Remove scrollbars from all tables

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#301]
Only the page itself should scroll, not the table inside the page. The whole table should be visible to the page, even if the page extends beyond the window viewport.

**Comment by brianwdavis** [comment]
We decided that instead tables should dominate pages they're on, and remove scrolling from the PAGE, and just fit the table to the viewport for scrolling.

**Comment by mikahpinegar** [comment]
this is resolved
