### ISSUE TITLE
put Map on Sensors

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#326]
1. pull gps point from parsed sensor install form
2. connect the gps location in the sensor table to a google map on the dashboard
so users can pull up maps on their phone to find the sensors in the field

**Comment by brianwdavis** [comment]
Need to check with Rick and see if that part of the API is working yet

**Comment by brianwdavis** [comment]
This is now going to be a separate component with a link from each sensor page. Will be reused other places too. Will eventually be on the sidebar probably.

- Pull the `locations?` endpoint, which should return up to 20 latlongs
- show "corners" as one color
- "sensor" as another color
- have some method to show live user location relative to a point. either open native maps app on device or show it in the react component

**Comment by brianwdavis** [comment]
Looking good so far, want to keep an eye on it before closing as new data comes in

**Comment by brianwdavis** [comment]
#637
