### ISSUE TITLE
Enrollment/Site information view

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/tech-dashboard#38]
## Form Pop Up
1. Year
2. Confirm no irrigation on site
3. lab or partner code - pull down menu Aurelie working on, renaming "states" table to affiliation
4. Prior grower?
    Yes - as user types last name, matching names are searched for
    No - enter last name
5. How many sites will this grower have this year?
6. <<INSERT random generated 3 letter codes here from unused codes list>>  Note* for 2020, codes are already assigned.  Sarah is collecting that info to send to Aurelie.

______________________________________________________________________________________________
## Table View - in the SITE View
1. Which protocols will be on site? (don't do this in 2020)
2. Grower Phone # (if new grower)
3. email (if new grower) - or EDIT if old
4. extension agent contact info (free form field)
5. Field address - not the farm address.  
6. Lat/long Use map pullout to have user correct field as need from the address look up function
     Lat/long for this purpose is stored in the "site information" table
7. Unenroll field button - Note, inactive fills all null cells with -999.  Any cells containing data will remain filled.  Confirm unenroll?

**Comment by saseehav** [comment]
sorry, Rohit, I dropped the ball on this one.  Our next objective is to get this site enrollment done on the dashboard.  @rbandooni 
when you get a chunk of time, let's tackle this with Aurelie who has loaded the sites for AL, NC, GA this year
