### ISSUE TITLE
Need to be able to view Producers to update email and and name etc

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#381]
We should have a view like Site Info but it's Producer info.

Producer ID, first name, last name, phone, email, array of codes enrolled, array of years enrolled, edit button

Not sure if that's implemented in the API yet? (should be)

**Comment by brianwdavis** [comment]
See **Producers** section of https://weather.aesl.ces.uga.edu/onfarm for an output endpoint, edit endpoint needs to be developed.

We discussed slapping together a PHP endpoint for editing that can be transitioned over to the production API later.

**Comment by brianwdavis** [comment]
In table, refer to `last_name` as "Last Name or Organization/Corporation Name" or similar verbiage, so that individuals have first and last names but businesses have just the one.

**Comment by brianwdavis** [comment]
We want to shift to the production API: api.precisionsustainableag.org/onfarm

**Comment by brianwdavis** [comment]
Need to figure out how to prevent API from caching result and force a new fetch.

**Comment by rbandooni** [comment]
We also need the 'dev' version of the API to be able to fetch all the existing "test" producers. This is crucial in testing features like edit/update on the front end.

**Comment by brianwdavis** [comment]
Good topic for discussion tomorrow

**Comment by screberg** [comment]
This maybe total ignorance, but I've noticed that Postman always uses a "no
cache" head.  Could we use that?
`Cache-Control: no-cache`

Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***

**Comment by brianwdavis** [comment]
I feel like that comment about caching is about a different issue, isn't it?

**Comment by brianwdavis** [comment]
@rbandooni did adding a timestamp resolve caching? Do we need this `Cache-Control: ` header instead?

**Comment by screberg** [comment]
I guess there are multiple levels of cache control

https://www.imperva.com/learn/performance/cache-control/


Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***
