### ISSUE TITLE
Kobo forms view

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#393]
1. A page where a given user can see what forms were submitted and on what date. We can use the column `kobo.asset_name` to group them, and the `kobo.timestamp` to sort them. To filter down to the user, every JSON entry has a field `"_submitted_by"`, and the names correspond to the viewable states: AL -> `al_psa`, NC -> `nc_psa` etc. 
 >  Need to check with @saseehav about people like indigo, what's their kobo username?

2. From this list, the user should be able to click on a row and see a pretty-printed JSON of the form. No need to parse/edit it at this step, there should be some auto-formatter library out there.

3. From that view, there should be a COMMENT button that behaves like the ones in All Data views. I feel like there will be differences in behavior, auto-tags, metadata? So we need to look at a prototype of that and react to it.

**Comment by saseehav** [comment]
Kobo username for Indigo: indigo_psa
should be in a sql database in kobo passwords table too. will try to update this every time a user gets made. we will make some for SHP coming soon.

**Comment by brianwdavis** [comment]
Update this week:

We have this view partially working using the kobo native API. To be implemented on this version:
1) Filter by username (from the `kobo_passwords` table) (`_submitted_by` field)
2) Comment button to alert `data_corrections`
3) Make each card go to its own page instead of popup modal
4) Get rid of "social science group" separate section, they're all PSA forms

**Comment by brianwdavis** [comment]
Sufficiently done for this version #406, will revisit after user feedback

**Comment by brianwdavis** [comment]
filter keywords TESTING and DEPRECATED to not show forms from the landing page

**Comment by brianwdavis** [comment]
Add name of form to the page that shows the content of the submissions
