### ISSUE TITLE
fill site_information.state upon enrollment or editing of location data

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#394]
The permissions checking for affiliations flow is not acting as intended. 
Ex: When a farm is enrolled under the 'MD' affiliation but the states is entered as PA - those sites appear in the user's permissions for the PA affiliation at Penn State.
The 'state' column in the user table really is 'affiliation' but is not acting as such.

**Comment by brianwdavis** [comment]
Side effect of old sites located in Pennsylvania being part of MD team affiliation. Do we want to edit old sites to match the MD affiliation and not PA anymore?

**Comment by brianwdavis** [comment]
In Site Info view, change "State" to "Affiliation". We will be adding a physical State column to the DB as well

**Comment by brianwdavis** [comment]
There already exists a physical state column `site_information.state`, that needs to be filled upon enrollment/edit

**Comment by brianwdavis** [comment]
Suspect that auto populating is not happening yet

**Comment by rbandooni** [comment]
I think this has been resolved. Needs testing

**Comment by brianwdavis** [comment]
This has not been resolved.
