### ISSUE TITLE
Move Raw Site Enrollment Data into the postgres Crown DB

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#42]

**Comment by screberg** [comment]
Is this referring to the data in google sheets?  Can you stick the link in here?

**Comment by saseehav** [comment]
Link to google sheet for 2020 Site Enrollment: https://docs.google.com/spreadsheets/d/1XIzLjH6US0iOr1SOqkS2S2Xo1P1oxj5KjEwYTghAlsg/edit#gid=15865789

To answer 'referring to data in google sheets?': No, I was thinking that we would have data entered from a tech dashboard by now for this issue.  Didn't know if it would go into 'Raw' database first to be dumped and then parsed into Crown_db.  This is reference to how we envisioned all data going into raw first, but this can likely be linked from tech dashboard directly to Crown_db without parsing.
