### ISSUE TITLE
biomass view

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#425]
The defaults from this endpoint are what we want for the "Biomass Farm Values" view. "Collected Values" view still to come.

The usual sort and filter by Year and Affiliation, don't need to show lat long, flag columns.

https://api.precisionsustainableag.org/onfarm/biomass

**Comment by brianwdavis** [comment]
column names:
subplot becomes Rep
species becomes Cover Crop\nSpecies
"Uncorrected (kg/ha)"
"Ash-Free (kg/ha)"
"%N by NIR"
"%N by Combustion" (is this in the API?)
"%C by Combustion"
"Moisture water:dry matter"

**Comment by brianwdavis** [comment]
round kg/ha views to nearest integer

**Comment by brianwdavis** [comment]
Still need to rename cols and round kg/ha

Possible dream feature: put a toggle in the upper right corner that passes a state to the table, which tells the kg/ha cols to be in lbs/ac: multiply the kg/ha value by .8922 and relabel the col to lbs/ac

**Comment by rbandooni** [comment]
> "%N by Combustion" (is this in the API?)
> "%C by Combustion"

I don't see these in the API?

**Comment by brianwdavis** [comment]
Add "C:N" (cn_ratio) 
Put C:N next to "%N by NIR" in the table

Don't need to do C or N by combustion columns anymore

**Comment by brianwdavis** [comment]
Sticky header
dynamically get viewport size and make table height that size to eliminate double scrollbars if possible
