### ISSUE TITLE
Make the Site Table in PostGres 'Private'

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#43]
This information that links 'Producer ID' to last name and contact needs to start being thought of as 'secure' or private data.  This will only be viewed by the state who entered the data and a set amount of 'Admin' users

**Comment by aureliemponcet** [comment]
The **producer_ids** table (which associates the unique producer_ids to a grower's name, email, and phone number) is now only accessible by _CROWNadmin_ (the admin user) and _shinyuser_ (read only user that only Brian will use to run his shiny app, which queries data based on the growers' last names). It has been hidden from **generaluser** (the read only user that will be provided to modelers and postdocs).

**Comment by saseehav** [comment]
Thanks Aurelie!
