### ISSUE TITLE
comments bugfixes

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#447]
1. When you click the submit comment button, the comment text vanishes while the button greys and changes to "creating comment", would like the text to persist during this
2. issues should be filtered by tagged affiliation when showing up in the front end Issues view

**Comment by brianwdavis** [comment]
@mikahpinegar any progress on this?

**Comment by mikahpinegar** [comment]
just saw this was assigned to me, i will fix this today. sorry for the delay.

**Comment by brianwdavis** [comment]
just need to change affils to chips
