### ISSUE TITLE
Change menus

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#474]
Feedback: Change Menu names

Saying "Water Sensors" in 2 places is confusing for novice users.
They don't understand that "Devices" includes Water Sensors and then why "Water Sensors" as a menu exists too. Can we consolidate Water Sensors into a single location (away from Devices) and call it Water Sensors > 'Device Status' and 'Installed'

**Comment by saseehav** [comment]
Also - I don't know what "Center Depth" is
![image](https://user-images.githubusercontent.com/49722541/117979784-47732600-b301-11eb-8949-f3a6b931d43c.png)

**Comment by brianwdavis** [comment]
- Timeline
- Protocols
- Site enrollment
- Producer Info
- Site Info
- - Contact and Location
- - Dates
- Biomass
- - Farm values
- Water Sensors
- - Raw View/Status (what used to be under Devices)
- - Chart View (the new chart page)
- - Legacy Chart View
- Stress Cams
- - Raw View/Status
- Issues
- Forms
