### ISSUE TITLE
Issues not showing up from the Comments Forms

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#477]
Users are using the "comments" feature on the tech dashboard under "Forms" but comments are not showing up in "Issues"
![image](https://user-images.githubusercontent.com/49722541/118174732-2f80cc80-b3fd-11eb-9a19-074de04adfe8.png)

 I wrote a title of my issue, and the issue (please delete the gps form XNM) in a comment box. Then when I submit my comment, it appeared for me in green that it was submitted. However, when I went in “issues” to verify that, it’s appearing “no issues”.

How should I proceed?

Thank you,

Tauana

**Comment by saseehav** [comment]
Also - I see no "Data Corrections" Issues for 9 days. Are people really not submitting issues/ comments/ corrections or is there a problem?

**Comment by saseehav** [comment]
Still no comments showing up. Tauna accepted the GitHub invite to the Repo and then sent me this message: 

I am unable to send my comment. When I click to send my comment appears “creating comment” (you can see in the print screen attached), and the screen freezes and does not create my comment. I double checked in the “issues” and its appearing “no issues”.

 
<img width="799" alt="Screen Shot 2021-05-19 at 2 00 58 PM" src="https://user-images.githubusercontent.com/49722541/119504234-c6248600-bd39-11eb-9638-415f5c5affcc.png">

**Comment by saseehav** [comment]
Today I tried to submit my comment again and I was unable to do that, the problem is the same that I wrote you last week. Is there any other way that I can follow to delete the GPS form for XNM code?

**Comment by saseehav** [comment]
Then when I go to submit an issue for Tauna I get 2 comment boxes in the same screen
![image](https://user-images.githubusercontent.com/49722541/119504599-21567880-bd3a-11eb-83b7-aab9675fcfb6.png)

**Comment by brianwdavis** [comment]
@mikahpinegar When you click comment on ONE form on a page, ALL forms get a comment box opened:
![image](https://user-images.githubusercontent.com/13338560/121049900-224dc800-c786-11eb-8c3f-1940ccebf9b5.png)
