### ISSUE TITLE
use wsensor_install endpoint for coloring sensor-visuals card

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#482]
- for each year chip pull the `raw?table=wsensor_install` endpoint
- for each code that you're already getting from `raw?table=site_info`, color the card green if there is >=1 record for subplot 1 and subplot 2
- add an info text line saying "form registered X days ago" based on the `time_begin` column

bonus: this gives you lat/longs to cache for showing a map on the next page

**Comment by rbandooni** [comment]
Choose the latest timestamp within each rep/subplot and then show the relative time

**Comment by brianwdavis** [comment]
Looks like this is working!
