### ISSUE TITLE
Step 2: associate node and gateway ids with site code

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/tech-dashboard#51]
Sarah knows this better, but somewhere there is an allocation table associating these attributes and it will need to be pulled in alongside the hologram pull

**Comment by screberg** [comment]
device id is metadata tag in hologram
to connect with code, need to look at sensor allocation table in crowndb

**Comment by screberg** [comment]
when a technician views the sensors info it queries both the raw and crowndb

**Comment by screberg** [comment]
Should we switch device names to be the exact same as gateway id?  Check in with alondra

**Comment by saseehav** [comment]
To associate nodes and gateways from raw Hologram data use Serial # in Hologram and associate it with code in Kobo Form psa_sensor_install.  This is needs to be parsed from the raw forms through to the Crown_DB.  @brianwdavis will move that form into crown_db into what table?  what is the new table called to make this association? @aureliemponcet and @brianwdavis

**Comment by saseehav** [comment]
After linking serial # of Gateway and Nodes to code, then match code to state in Crown_db

**Comment by screberg** [comment]
Changed our minds.  Two views.  One is the most recent info which uses Hologram API only.  Then there is the crowndb visualisations for the tech dashboard suggested by alondra.  These are fully parsed data connecting site codes and all columns
