### ISSUE TITLE
Step 1: partial parse of hologram data

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/tech-dashboard#52]
Replace the use of Slack as a system of status checking sensors. It can look like the current info displayed in the "barc-test" channel on slack.  The goal is to replace the slack channel notification and test.  We do not want to use slack in future iterations for this task.

Match state "tag" to access control.  Keep current "devices" view on dashboard the same with green, white and red.  Note using the Hologram API for everything except access permission which is stored in MySQL

**Comment by saseehav** [comment]
@rbandooni @screberg 
as of Data Flow Meeting 4/14/2020 this is still the first step.  Other things to parse from this Raw Data String include 'tags'.  This appears as the second thing "hhs" in this slack channel string example:

- V2020.03.25~hhs~21000047~3.79~19.00~0~0.03~2020-4-15_12:04:01_UTC

- 8:05
V2020.03.25~hhs~18000127~3.99~18.50~0~0.00~2020-4-15_11:20:00_UTC~D14Acclima TR315H2.790071101~+0~0.0~16.9~1.0~0~0~E14Acclima TR315H2.790071083~-0~0.0~17.3~1.1~0~0~F14Acclima TR315H2.790071085~-0~0.0~17.1~1.1~0~0~T14Acclima Temp010.234000011~+10~17.07~-35

**Comment by saseehav** [comment]
For more information on what information is needed from Hologram see the Data Flow notes: https://docs.google.com/document/d/1tydsU_uxHimlaTDaQZX_lCLQ0_dyNP8v2t6KpBl97_I/edit

**Comment by saseehav** [comment]
Is this issue considered closed now that we are pulling directly from Hologram Devices?

**Comment by rbandooni** [comment]
This would close automatically once @screberg approves #66
