### ISSUE TITLE
Comments not working 

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#521]
![image](https://user-images.githubusercontent.com/49722541/120347375-35feb780-c2ca-11eb-89d4-3b207562e01d.png)

**Comment by brianwdavis** [comment]
Should be working in #531

**Comment by saseehav** [comment]
Kip is using Chrome.
He thinks his comment is submitting, even though he has not confirmed his invite to the PSA repository. Can we get an error message when the comment does not submit?

**Comment by saseehav** [comment]
Kip: Accepted invite and entered comment again.  I doubt it worked, but you can check.  It never seems like the comment was accepted.  It just says creating comment, but never goes beyond that on my screen.

**Comment by brianwdavis** [comment]
Appears to be working as of this week
