### ISSUE TITLE
Status indicator/splash page

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#529]
some way to inform users when something is broken:
- Is Hologram's API working?
- Is the onfarm API working?
- Is the database server itself live? (probably won't be any different from the onfarm API VM)
- Is Auth0 working?
- any other services we depend on?

Just thinking about a little green light indicator somewhere before login and maybe also in the sidebar. That way we can help catch issues like the SSL cert quickly.

**Comment by brianwdavis** [comment]
PHP API

**Comment by mikahpinegar** [comment]
we should add the azure function to this api check
