### ISSUE TITLE
Still struggling with "fetching more" from Hologram API

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#536]
On FIrefox, with screen size of however many pixels this screenshot has on a Mac.

![image](https://user-images.githubusercontent.com/13338560/121071702-4917f880-c79e-11eb-8d57-50f7cbd22990.png)

**Comment by rbandooni** [comment]
Related to #538

**Comment by brianwdavis** [comment]
This is intermittent for me though, sometimes it loads fine and other times nothing happens. I just tried it again and it scrolled smoothly without ever showing the loading icon.

**Comment by brianwdavis** [comment]
1411 pixels wide
1194 pixels tall
