### ISSUE TITLE
Undesirable behavior on back button, forgetting chip selections

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#543]
If a user selects a chip to filter on water sensors Chart View, then chooses a card to view, then goes back using either the browser functionality or the button at the top, the app doesn't remember the chip selection. Is this fixable?

**Comment by mikahpinegar** [comment]
the back button was working for me but not the browser back button. i figured out how to persist when using the browsers back button, do we still need the other back button?

**Comment by brianwdavis** [comment]
This fix worked, need to propagate to all other clickable backs.

**Comment by brianwdavis** [comment]
Related to #601 I think

**Comment by mikahpinegar** [comment]
all logical backs are working
