### ISSUE TITLE
Dashboard improvement : Device Status /Chart View

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/tech-dashboard#557]
Dashboard improvement suggestion: @brianwdavis 

It can be really annoying going between device status and chart view when wanting to see what is going on at a specific farm.  It would be nice if you could select the farm on one page (UAN Iron Horse Farm), clicking on the icon would lead you to the chart view for that farm, and then while you are on chart view there would be an arrow button you could click that would lead you to the device status view for that particular farm.  This would result in a lot less clicking around back and forth.

**Comment by brianwdavis** [comment]
I need to think about how to prototype this functionality.
