### ISSUE TITLE
Chart View  Y axis

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/tech-dashboard#561]
In chart view the Y axis on the VWC graphs is not standardized and changes with each graph.  Can we have a set y axis so graphs are easier to compare?
![Screenshot 2021-06-22 112044](https://user-images.githubusercontent.com/64480167/122952247-e735c200-d34b-11eb-8b5b-439f1f6a6b69.png)

**Comment by brianwdavis** [comment]
What should the range be on each chart for each measurement type?
VWC: 0-50
Soil temp: -10 - +40
Litterbag temp: 0-50

leave the node health as is

**Comment by rbandooni** [comment]
vwc still needs to be in the range
