### ISSUE TITLE
Visualization Ideas for Sensors Data Live View

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#59]
- Gateway Initialization string with time stamp

- Gateway Voltage over time

- Node Voltage over time

- Signal Strength

- Node (each per gateway) with % VWC and temp

Form more ideas: https://docs.google.com/spreadsheets/d/1uS5zUVv5ALF5plxuskKSDGffwl2XX41DfHGGv_ycZsA/edit#gid=1818536918

**Comment by saseehav** [comment]
@rbandooni how are the visualizations going?  Did you have to use old data or has the new data gone live yet?

**Comment by rbandooni** [comment]
@saseehav It’s going good. Can’t wait to publish this new version!
