### ISSUE TITLE
Information for Parsing the Hologram String

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#60]
The order of the data string for Gateways and Nodes: 
https://docs.google.com/spreadsheets/d/1uwCadZ4SFWu45WO2qcbT7PEGb24SruGUUx_kUoRhSV0/edit#gid=0

**Comment by brianwdavis** [comment]
Table schema layout to connect these headers to DB

https://docs.google.com/spreadsheets/d/1AqQ0j0mfNxKNU8u3s0NMxRO_-8DVzPzMzpEgAvC7Uuk
