### ISSUE TITLE
Site enrollment: Should fill `protocol_enrollment` table via API based on checkboxes

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#646]
I will provide an array below of checkboxes to ask about on Site Enrollment, those text labels will be concatenated and returned in the AP as a `protocols` column.

**Comment by brianwdavis** [comment]
If value = -999, grayed out checkbox. If value = NULL or 0, empty checkbox, allow user to check to set to 1. If value = 1, filled checkbox, allow user to uncheck to set to 0. All columns except `code`, `cid`, `notes`

**Comment by mikahpinegar** [comment]
the url for the update protocol_enrollment api is `/crowndb/protocol_enrollment/QUU`

**Comment by mikahpinegar** [comment]
this can be closed
