### ISSUE TITLE
Improve render time on water sensor chart view

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#657]
The spinner seems to only be for the API request time, then there's multiple seconds of white screen before the charts render. 

We had previously discussed some ideas to speed up render time since there's so many points (multiple tabs that only render when requests/on background; filtering out to some subsample of points instead of the whole response object), and we should revisit those this winter. 

In the meantime, can we have the spinner continue, or a new spinner/helper text be present while rendering?

**Comment by brianwdavis** [comment]
https://www.highcharts.com/docs/advanced-chart-features/boost-module

**Comment by brianwdavis** [comment]
The tabs now need to be styled to be more obvious "separate tabs", which they currently don't read as visually. Also @mikahpinegar  says that the API call is pulling down the data once for each tab, instead of once for the page and passing it to the tab. However, node/gateway calls should be made for the first tab, TDR for the second, and TDR/ambient for the third, so divide that however is logical.

**Comment by mikahpinegar** [comment]
to do:
- make one parent component that fetches the data and memoizes it 
- pass that data into each sub component for each tab (vwc, temp, node). right now each time a tab is clicked it refetches the api endpoint 
- first (default) tab should be node

**Comment by mikahpinegar** [comment]
@dearpriyankasa, can you look into using the boost graphing library for water sensors and the stress cams? the performance of highcharts has been problematic and people seem to say boost is better

**Comment by dearpriyankasa** [comment]
Done in PR: https://github.com/precision-sustainable-ag/tech-dashboard/pull/856

**Comment by brianwdavis** [comment]
@mikahpinegar are there dangling issues from the refactoring list you made above? Should we just make a fresh issue?
