### ISSUE TITLE
Site enrollment rework

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#711]
- [x] year dropdown -> "Cash crop year"
- [x] Under Existing grower, the "show sites" should be shown already for all producers, no more button
- [x] After a code is assigned, change "Edit" button to "Open map to edit"
- [x] After submission, auto-navigate to "Contact and Location"
- [x] On opening "Contact and Location" any time, have all the groupings uncollapsed by default
- [ ] On editing location details, the Lat and Long shouldn't be `<input type="number">`, instead it should be a text field with regex to allow only digits and a single period with an optional initial minus sign (make sure that pasting in still works)

**Comment by mikahpinegar** [comment]
@dearpriyankasa, could you tackle the last 2 tasks in this isse?
