### ISSUE TITLE
forms view not working

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/tech-dashboard#717]
Shows 'Fetching Data...' response but that is it.  Tested on Chrome by chris and sarah.  Callers on on-farm meeting reported the problem.

**Comment by mikahpinegar** [comment]
we're working on a fix for that now, it should be resolved shortly

**Comment by mikahpinegar** [comment]
this is resolved now. there was an issue with python mysql connector on a new version of azure function
