### ISSUE TITLE
Setup auto indenting 

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#721]
- convert existing files to follow a set of rules for indenting
- ideally setup a config file that will make it consistent for all developers who clone the repo (similar to .eslint.js config file)
- document what extensions need to be installed by developers to enforce consistent indenting

**Comment by dearpriyankasa** [comment]
Have updated the document with the editor settings that I use on my local: https://precision-sustainable-ag.atlassian.net/wiki/spaces/TD/pages/33235/Deploying+Locally

**Comment by mikahpinegar** [comment]
ok, after looking into it a bit more what i really want is to have eslint use airbnb style guide as outlined here (https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a and i also had to do this to get it working on my branch https://github.com/airbnb/javascript/issues/2202#issuecomment-826329342). this will take some redoing but hopefully won't be too painful. we had discussed following airbnb style guide in the past but this will enforce it for all developers. can you update all the files to follow this and compile correctly @dearpriyankasa? also feel free to add any other prettier configs that you think would be helpful
