### ISSUE TITLE
Resolve Security Vulnerabilities

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#751]
There are currently 16 security vulnerabilities when running `npm install` for the tech dashboard repository. Below is a list of vulnerabilities.
- `ansi-html`
- `ansi-regex`
- `immer`

To resolve these, update the package to the newest version if a patch is available. If a patch is not available you will have to research how to resolve it, this will be the case for ansi-html because there is no patch available.

**Comment by rationalyt** [comment]
[Package_Issues.docx](https://github.com/precision-sustainable-ag/tech-dashboard/files/7747349/Package_Issues.docx)

The document consists of packages classified according to its effects. I couldn't find ansi packages as issues in the logs while installing. Can you please share the logs for it. Could it be system dependent ?
