### ISSUE TITLE
On editing site location, if no pre-existing latlong, multiple undesired behaviors

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#785]
1. google map should auto populate with address if given, the multi way sync between all the fields seems brittle
2. when opening the next site with no lat long, google map is auto populated with the LAST site's lat long as a pin, instead of nulling it out

**Comment by mikahpinegar** [comment]
unlink field address and google maps search. on update set lat/lng state variables to default value

**Comment by mikahpinegar** [comment]
resolved on dev
