### ISSUE TITLE
Have comments button on dates view

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#789]
Just like other tables

**Comment by mikahpinegar** [comment]
isn't this already a thing?

**Comment by mikahpinegar** [comment]
right now each code has a comment button in site information -> dates. is there some other behavior we want?

**Comment by mikahpinegar** [comment]
going to move the calendar view button to the sidebar

**Comment by mikahpinegar** [comment]
moved on dev
