### ISSUE TITLE
Decomp Bag table won't show last 4 rows

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#818]
Will display 20 of 24 rows. When I select the page next arrow, it won't page over

**Comment by mikahpinegar** [comment]
ok the problem here is that pagination is supposed to be done using an api so next page doesn't scroll to the next set of data already fetched from the api but would try to fetch new data by default. i'm going to set the default page length to the size of the data for decomp bags

**Comment by mikahpinegar** [comment]
wait maybe not. it looks like something else was breaking it. once i removed the pagination options changing pages works fine. i'm investigating further now

**Comment by mikahpinegar** [comment]
this is actually only a problem in production for some reason. the error is `Uncaught TypeError: e.props.onChangePage is not a function`

**Comment by mikahpinegar** [comment]
this was actually a problem for all of our tables built on material-table. it's resolved now
