### ISSUE TITLE
"rep" -> "subplot" and "trt" -> "treatment"

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#832]
Anywhere that an API call is depending on those fields, use the updated preferred column name.

I **think** this is only for water sensor chart view and stresscam.

**Comment by dearpriyankasa** [comment]
I updated this where I was using it in stress-cams. Do you want me to update at all other places as well?

**Comment by brianwdavis** [comment]
Yes
