### ISSUE TITLE
Not re rendering when switching between water sensors, decomp bags, and stress cams chart view

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#842]
If I load water sensors chart view page and then switch to stress cams chart view page the cards stay colored when they shouldn't be. The same is true the other direction (if I render stress cams first and then switch to water sensors there's no color when there should be). The same goes for decomp bags as well

**Comment by dearpriyankasa** [comment]
Fixed in PR - https://github.com/precision-sustainable-ag/tech-dashboard/pull/851
