### ISSUE TITLE
First component to fix when protocols gets added to API: dates forecasting

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#854]
One of the next big pushes for the API will be passing the protocols table as an object in with site info. For the dates view, even if a site is "biomass-only" (ie not enrolled in decomp), there shouldn't be forecast dates for those sites shown.

**Comment by brianwdavis** [comment]
This is correct behavior! Can we replicate this effect on the calendar view? I'm not sure how that's implemented.

**Comment by mikahpinegar** [comment]
this is done
