### ISSUE TITLE
Search on decomp view isn't working

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#855]
To reproduce, select 2021 and search for "SHX". You can see it scrolling down, but the search returns nothing.

**Comment by dearpriyankasa** [comment]
Done in PR: https://github.com/precision-sustainable-ag/tech-dashboard/pull/865

**Comment by brianwdavis** [comment]
Working!

**Comment by brianwdavis** [comment]
The search bar state is persisting across components. If you type something into Search on Decomp, it still filters when you click over to Water Sensors chart view. Should revert to empty when you switch pages.

**Comment by dearpriyankasa** [comment]
Search field state updation fix in PR: https://github.com/precision-sustainable-ag/tech-dashboard/pull/869
