### ISSUE TITLE
comments on water sensor and stresscam chart view placeholder text

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#868]
Ideally the comment button should be on each chart in water sensors/stresscams, and make sure to capture code, treatment, rep

**Comment by mikahpinegar** [comment]
did we ever figure out what's up with this issue @brianwdavis?

**Comment by brianwdavis** [comment]
Restarting this issue with a new focus: Can we put placeholder text inside the comment box on load?

"Make sure to include treatment, rep, which sensor(s)/depth(s) are problematic; etc. Include as much detail as possible."
