### ISSUE TITLE
years chips reverse order after clicking an affiliation or year on Biomass values

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/tech-dashboard#925]
Condition one:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/13338560/172433891-faa98c1e-4cc0-4130-a05d-3ede56e071ce.png">

Then click to condition two:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/13338560/172434090-bea6db5c-7d09-4156-a139-d045757fedf3.png">

**Comment by mikahpinegar** [comment]
this bug is only on firefox

**Comment by brianwdavis** [comment]
Well we have important users on Firefox ;)

**Comment by brianwdavis** [comment]
I'm on 100.0 which is very close to the latest, 2022-05-03

**Comment by brianwdavis** [comment]
Appears to be fixed for me as well on 101.01. I guess it's a specific rendering bug that's been fixed?

**Comment by azeng4499** [comment]
Ok, fantastic

**Comment by brianwdavis** [comment]
This issue will be superseded by the dropdown anyway.
