### ISSUE TITLE
Make years and affiliations a dropdown instead of chips

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#950]

**Comment by brianwdavis** [comment]
I like multiselect for this, in case you want to look at 2+ states at once
https://furqanzafar.github.io/react-selectize/#/
But @saseehav may think that's an unusual use case and that we want to filter to either just one or "all"

**Comment by brianwdavis** [comment]
Or this can be the testbed for mui-datatables from #952
