### ISSUE TITLE
editing dates text boxes are squished

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#971]
![pic](https://user-images.githubusercontent.com/55995241/176007104-dfa59e62-cec2-4775-af55-4ae5646599b8.PNG)
maybe stack them 2 high instead of 4 or widen the modal?

**Comment by ssharm1524** [comment]
Weird. What browser are you using? They look fine on safari to me so it might be a browser specific thing.

**Comment by brianwdavis** [comment]
Add farm code to title of modal please
